dbmigrate/api/urls.py
from django.urls import path

from . import views

app_name = "api"
urlpatterns = [
    path("employee", views.EmployeeListCreateView.as_view(), name="employee_list_create"),
    # path("<int:pk>", views.AboutRetrieveUpdateDestroyView.as_view(), name="detail"),
    path("department", views.DepartmentListCreateView.as_view(), name="department_list_create"),
    path("job", views.JobListCreateView.as_view(), name="job_list_create"),
]

dbmigrate/dbmigrate/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/", include("api.urls")),
    path("", views.index_view, name="index")
]

dbmigrate/dbmigrate/views.py
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render

@csrf_exempt
def index_view(request):
    """
    List all code snippets, or create a new snippet.
    """
    if request.method == "GET":
        return render(request, "index.html")

dbmigrate/dbmigrate/templates/index.html
<head>
    <title>Database Migrate</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    {% load static %}
    <link rel="stylesheet" href="{% static 'index.css' %}">
</head>

<body>
    <h1 class="jumbotron text-center">Database Migration</h1> <br><br>
    <h4 class="bg-primary text-center">Department Database</h1>
    <form accept-charset="UTF-8" action="{% url 'api:department_list_create'  %}" method="POST" enctype="multipart/form-data" class="text-center">
      <hr>
      <div class="form-group mt-3">
        <label class="mr-2">Upload your CSV file:</label>
        <input type="file" name="file">
      </div>
      <hr>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    </div> 
    <br><br>
    
    
    <h4 class="bg-secondary text-center">Job Database</h1>
    <form accept-charset="UTF-8" action="{% url 'api:job_list_create'  %}" method="POST" enctype="multipart/form-data" class="text-center">
      <hr>
      <div class="form-group mt-3">
        <label class="mr-2">Upload your CSV file:</label>
        <input type="file" name="file">
      </div>
      <hr>
      <button type="submit" class="btn btn-secondary">Submit</button>
    </form>
    </div> 
    <br><br>
    
    <h4 class="bg-success text-center">Employee Database</h1>
    <form accept-charset="UTF-8" action="{% url 'api:employee_list_create'  %}" method="POST" enctype="multipart/form-data" class="text-center">
      <hr>
      <div class="form-group mt-3">
        <label class="mr-2">Upload your CSV file:</label>
        <input type="file" name="file">
      </div>
      <hr>
      <button type="submit" class="btn btn-success">Submit</button>
    </form>
    </div> 
            
</body>

dbmigrate/dbmigrate/templates/result.html
<head>
    <title>Database Migrate</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    {% load static %}
    <link rel="stylesheet" href="{% static 'index.css' %}">
</head>

<body>
    <h1 class="jumbotron text-center">Database Migration</h1> <br><br>
    {% if success %}
    <h4 class="bg-success text-center">{{ message }}</h1>
    {% else %}
    <h4 class="bg-danger text-center">{{ message }}</h1>
    {% endif %}
    <div class="text-center">
        <a href="{% url 'index' %}" class="btn btn-primary text-center">Home</a>
    </div>
            
</body>